app/models/Cliente.py
from app.extesiones import db
from sqlalchemy.orm import relationship
from flask_login import UserMixin

class Cliente(db.Model, UserMixin):
    idcliente = db.Column(db.SmallInteger, primary_key=True)
    nombreCliente = db.Column(db.String(45), nullable=True)
    documentoCliente = db.Column(db.String(45), nullable=True)
    direccionCliente = db.Column(db.String(45), nullable=True)
    celularCliente = db.Column(db.String(45), nullable=True)
    contrasenaCliente = db.Column(db.String(256), nullable=True)
    
    @property
    def pl(self):
        return self.nombreCliente[0] if self.nombreCliente else None
    
    def get_id(self):
        return str(self.idcliente)

app/routes/Cliente_routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from app.extesiones import db
from app.models.Cliente import Cliente
from flask_login import login_user, current_user, logout_user, login_required
from flask_bcrypt import Bcrypt

bp = Blueprint('Cliente', __name__)


@bp.route('/Cliente')
def index():
    data = Cliente.query.all()
    return render_template('Cliente/index.html', data=data)


@bp.route('/Cliente/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
        nombre = request.form['nombre']
        documento = request.form['documento']
        correo = request.form['correo']
        celular = request.form['celular']
        contrasena = request.form['contrasena']
        
        NCliente = Cliente(nombreCliente=nombre, documentoCliente=documento, direccionCliente=correo, celularCliente=celular, contrasenaCliente=contrasena)
        db.session.add(NCliente)
        db.session.commit()
        
        return redirect(url_for('Cliente.index'))

    return render_template('Cliente/add.html')

@bp.route('/Cliente/registro', methods=['GET', 'POST'])
def registro():
    if request.method == 'POST':
        nombre = request.form['nombre']
        documento = request.form['documento']
        correo = request.form['correo']
        celular = request.form['celular']
        contrasena = request.form['contrasena']
        
        NCliente = Cliente(nombreCliente=nombre, documentoCliente=documento, direccionCliente=correo, celularCliente=celular, contrasenaCliente=contrasena)
        db.session.add(NCliente)
        db.session.commit()
        
        return redirect(url_for('Administrador.login'))

    return render_template('Cliente/registro.html')

@bp.route('/Cliente/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    cliente = Cliente.query.get_or_404(id)

    if request.method == 'POST':
        cliente.nombre = request.form['nombre']
        cliente.documento = request.form['documento']
        cliente.correo = request.form['correo']
        cliente.celular = request.form['celular']
        db.session.commit()
        return redirect(url_for('Cliente.index'))

    return render_template('Cliente/edit.html', cliente=cliente)
    

@bp.route('/Cliente/delete/<int:id>')
def delete(id):
    client = Cliente.query.get_or_404(id)
    
    db.session.delete(client)
    db.session.commit()

    return redirect(url_for('Cliente.index'))

app/templates/Cliente/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='estilo.css') }}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/css/bootstrap.min.css">
    <script src="{{ url_for('static', filename='bootstrap-5.3.0/js/bootstrap.bundle.js') }}"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <title>Registro Cliente</title>
</head>
<body>
    <h1>Registro Cliente</h1>
    <form action="{{ url_for('Cliente.add') }}" method="post">
        <label for="nombre">Nombre:</label>
        <input type="text" id="nombre" name="nombre" required class="form-control">
        <label for="documento">Documento:</label>
        <input type="number" id="documento" name="documento" required class="form-control">
        <label for="correo">Correo:</label>
        <input type="email" id="correo" name="correo" required class="form-control">
        <label for="celular">Celular:</label> 
        <input type="number" id="celular" name="celular" required class="form-control"  >
        <label for="contrasena">Contraseña:</label> 
        <input type="number" id="contrasena" name="contrasena" required class="form-control"  >
     
        <button type="submit">Agregar Cliente</button>
    </form>
</body>
</html>

app/templates/Cliente/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='estilo.css') }}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/css/bootstrap.min.css">
    <script src="{{ url_for('static', filename='bootstrap-5.3.0/js/bootstrap.bundle.js') }}"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <title>Editar Nombre</title>
</head>
<body>
    <h1>Editar Nombre</h1>
    <form action="{{ url_for('Cliente.edit', id=cliente.idcliente) }}" method="post">
        <label for="nombre">Nombre:</label>
        <input type="text" id="nombre" name="nombre" value="{{ cliente.nombreCliente }}" required class="form-control">
        <label for="documento">Documento:</label>
        <input type="text" id="documento" name="documento" value="{{ cliente.documentoCliente }}" required class="form-control">
        <label for="correo">Correo:</label>
        <input type="text" id="correo" name="correo" value="{{ cliente.correoCliente }}" required class="form-control" > 
        <label for="celular">Celular:</label>
        <input type="text" id="celular" name="celular" value="{{ cliente.celularCliente }}" required class="form-control">
        <button type="submit">Actualizar Cliente:</button>
    </form>
</body>
</html>

app/templates/Cliente/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/css/bootstrap.min.css">
    <script src="{{ url_for('static', filename='bootstrap-5.3.0/js/bootstrap.bundle.js') }}"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <link rel="stylesheet" href="{{ url_for('static', filename='estilo.css') }}">
    <title>Clientes</title>
</head>
<body>
    <div class="container">
        <h1>Clientes</h1>
        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Documento</th>
                    <th>Correo</th>
                    <th>Celular</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for Cliente in data %}
                    <tr>
                        <td>{{ Cliente.idcliente }}</td>
                        <td>{{ Cliente.nombreCliente }}</td>
                        <td>{{ Cliente.documentoCliente }}</td>
                        <td>{{ Cliente.direccionCliente }}</td>
                        <td>{{ Cliente.celularCliente }}</td>
                        <td>
                            <a href="{{ url_for('Cliente.edit', id=Cliente.idcliente) }}" class="btn btn-primary">Editar</a>
                            <a href="{{ url_for('Cliente.delete', id=Cliente.idcliente) }}" class="btn btn-danger">Eliminar</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <a href="{{ url_for('Cliente.add') }}" class="btn btn-success">Agregar Cliente</a><br>
        <a href="{{ url_for('Administrador.index') }}" class="btn btn-secondary">Ir a Administrador</a>
    </div>
    <!-- Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/Cliente/registro.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='estiloi.css') }}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/css/bootstrap.min.css">
    <script src="{{ url_for('static', filename='bootstrap-5.3.0/js/bootstrap.bundle.js') }}"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <title>Registro Cliente</title>
</head>
<body id="bdy" class="bg    " >
    <div id="iss">
        <br>
        <center>
            <h1 id="tle">Registro</h1> 
        </center>
       
        <div id="ubic" >

            <img id="ubic" src="{{ url_for('static', filename='imagenes/logo(registro).jpg') }}" alt="" style="width: 35%; height: 35%; " >

        </div>

        <form id="fm" class="row g-3 needs-validation" action="{{ url_for('Cliente.registro') }}" method="post"> 
         
    
            <div class="col-md-9">
                <div><br>
                    <div id="sepr">
                        <div>
                            <label id="lbl" for="validationCustom01" class="form-label">Ingrese Su Nombre</label><br>
                            <input type="text" class="form-control" id="nombre" name="nombre" required>
                            <div class="valid-feedback">
                                Ok
                            </div>
                            <div class="invalid-feedback">
                                Ingrese su Nombre
                            </div>
                        </div>    
                        <div>
                            <label id="lbl" for="validationCustom02" class="form-label">Ingrese Su Documento</label><br>
                            <input type="number" class="form-control" id="apellido" name="documento" required>
                            <div class="valid-feedback">
                                Ok
                            </div>
                            <div class="invalid-feedback">
                                Ingrese su Documento
                            </div>
                        </div>
                    </div>
                    <div id="sepr">
                        <div>    
                            <br><label id="lbl" for="validationCustom03" class="form-label">Ingrese Su Correo</label><br>
                            <br><input type="email" class="form-control" id="edad" name="correo" required>
                            <div class="valid-feedback">
                                Ok
                            </div>
                            <div class="invalid-feedback">
                                Ingrese su Correo
                            </div>
                        </div>
                        <div>
                            <br><label id="lbl" for="validationCustom04" class="form-label">Ingrese Su Celular</label><br>
                            <br><input type="number" class="form-control" id="correo" name="celular" required>
                            <div class="valid-feedback">
                                Ok
                            </div>
                            <div class="invalid-feedback">
                                Ingrese su Celular
                            </div>
                        </div>
                    </div>
                </div>
        
                <div class="col-md-12">
                    <br><br>
                    <label id="lbl" for="validationCustom05" class="form-label">Ingrese su Contraseña</label>
                    <br><input type="password" class="form-control" id="contrasena" name="contrasena" required>
                    <div class="valid-feedback">
                        Ok
                    </div>
                    <div class="invalid-feedback">
                        Ingrese su Contraseña
                    </div>
                </div> 
                <br>
                <center><a class="shining-text" href="{{ url_for('Administrador.login') }}">Ya tienes una cuenta? Inicia Sesion!</a></center>
                <br><br>
                <div id="lbl" class="col-12">
                    <button id="lbl" class="btn btn-primary"  href="{{ url_for('Administrador.login') }}" type="submit" >Registrarse</button>
                </div>
            </div>
        </form>
    </div>
    
    <script>
        (() => {
            'use strict'
            const forms = document.querySelectorAll('.needs-validation')
            Array.from(forms).forEach(form => {
                form.addEventListener('submit', event => {
                    if (!form.checkValidity()) {
                        event.preventDefault()
                        event.stopPropagation()
                    }
    
                    form.classList.add('was-validated')
                }, false)
            })
        })()
    </script>
    <style>
        @keyframes shining {
            0% {
                color: #013cff;
            }
    
            50% {
                color: rgb(0, 251, 255);
                text-shadow: 0 0 50px rgb(170, 236, 255);
            }
    
            100% {
                color: #013cff;
            }
        }
    
        .shining-text {
            animation: shining 1s linear infinite;
            text-decoration: none;
        }
</body>
</html>