app/models/Productos.py
from app.extesiones import db
from sqlalchemy.orm import relationship

class Producto(db.Model):
    idProducto = db.Column(db.Integer, primary_key=True)
    nombreProducto = db.Column(db.String(45), nullable=True)
    detalleProducto = db.Column(db.String(45), nullable=True)
    precioProducto = db.Column(db.Integer, nullable=True)
    stockProducto = db.Column(db.Integer, nullable=True)
    Categoria_idCategoria = db.Column(db.Integer, db.ForeignKey('categoria.idCategoria'), nullable=False)
    imgp = db.Column(db.String(150), nullable=True)
    categor = db.relationship("Categoria")

app/routes/Administrador_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, render_template, redirect, url_for, request, flash
from app.models.Administrador import Administrador
from app.models.Cliente import Cliente
from flask_login import login_user, current_user, logout_user, login_required
from flask_bcrypt import Bcrypt
from app.extesiones import db


bp = Blueprint('Administrador', __name__)


@bp.route('/Administracion')
def index():
    data = Administrador.query.all()
    print("Data ", data)
    return render_template('Administrador/index.html', data=data)


@bp.route('/Admin/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
        bcrypt = Bcrypt()
        Correo = request.form['correo']
        Contrasena = request.form['contrasena']
        hashed_password = bcrypt.generate_password_hash(Contrasena.encode('utf-8'))
        new_admin = Administrador(correoAdm=Correo, contrasenaAdm=hashed_password)
        print(new_admin)
        db.session.add(new_admin)
        db.session.commit()
        
        return redirect(url_for('Administrador.index'))

    return render_template('Administrador/add.html')

@bp.route('/Admin/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    admin = Administrador.query.get_or_404(id)

    if request.method == 'POST':
        admin.Correo = request.form['correo']
        admin.Contrasena = request.form['contrasena']
        db.session.commit()
        return redirect(url_for('Administrador.index'))

    return render_template('Administrador/edit.html', admin=admin)
    

@bp.route('/Admin/delete/<int:id>')
def delete(id):
    
    admin = Administrador.query.get_or_404(id)
    
    db.session.delete(admin)
    db.session.commit()

    return redirect(url_for('Administrador.index'))


@bp.route('/', methods=['GET', 'POST'])
def login():    
    global tipo
    
    
    if request.method == 'POST':
        bcrypt = Bcrypt()
        username = request.form['correo']
        password = request.form['password']
        
        user = Cliente.query.filter_by(direccionCliente=username,contrasenaCliente=password).first()
 
        if user :
            
            tipo = 0 
            login_user(user)
            flash("Login successful!", "success")
            return redirect(url_for('Productos.index'))
        
        else:
            user = Administrador.query.filter_by(correoAdm=username).first()
            if user:
                tipo = 1
                if bcrypt.check_password_hash(user.contrasenaAdm, password):
                    login_user(user)
                    flash("Login successful!", "success")
                    return redirect(url_for('Administrador.index'))
                
    return render_template("/Administrador/login.html")


@bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.', 'info')
    return redirect(url_for('Administrador.login'))

app/routes/Carrito.py
from app.extesiones import db
from flask import Blueprint, render_template, request, redirect, url_for, render_template, redirect, url_for, request, flash
from app.models.Carrito import Carrito
from app.models.Productos import Producto
from app.models.Factura import Factura
from app.models.Administrador import Administrador
from flask_login import current_user
from datetime import datetime
from app.models.Detalle import Detalle
from flask_login import login_user, current_user, logout_user, login_required




bp = Blueprint('carritos', __name__)
carrito_compras = Carrito()

@bp.route('/ListarCarrito')
def listar():
    items = carrito_compras.getItems()
    
    
    
    
        
        
    return render_template('productos/List.html', items=items)

@bp.route('/ListarProductos')
def index():
    productos = carrito_compras.getItems()
    return render_template('Carrito/index.html', productos=productos)

@bp.route('/agregar/<int:id>', methods=['POST'])
def agregar_al_carrito(id):
    producto = Producto.query.get(id)

    cantidad = int(request.form.get('cantidad', 1))
    if producto.stockProducto < cantidad:
        return redirect(url_for('Productos.index'))

    carrito_compras.agregar_producto(id, cantidad)
    

    return redirect(url_for('Productos.index'))
    #return "Entra a agregar corrito"
    
    
@bp.route('/eliminar/<int:id>', methods=['POST'])
def eliminar_del_carrito(id):
    cantidad = int(request.form.get('cantidad', 1))
    carrito_compras.eliminar_producto(id, cantidad)
    return redirect(url_for('carritos.index')) if carrito_compras.tamañoD() > 0 else redirect(url_for('Productos.index'))
    #return "Entra a agregar corrito"

@bp.route('/realizar_compra')
def realizar_compra():
    total = carrito_compras.calcular_total()
    return render_template('realizar_compra.html', total=total)

# @bp.route('/generar_factura', methods=['POST'])
# def generar_factura():
#     total = carrito_compras.calcular_total()
#     # Aquí puedes almacenar la información en la base de datos (crear registros en Carrito y Factura)
#     # y luego limpiar el carrito de compras
#     carrito_compras.carrito = []
#     return render_template('factura.html', total=total)

@bp.route('/itemscarrito', methods=['GET', 'POST'])
def tCarrito():
    a = carrito_compras.tamañoD()
    print("Entra a carrito rutas", a)
    return f"Entra a carrito {carrito_compras.tamañoD()}"

@bp.route("/Carrito/factura", methods=["GET", "POST"])
@login_required
def generar_factura():
    
    carrito = carrito_compras.getItems()
    
    if carrito:  # Verifica si el carrito no está vacío
        fecha = datetime.now()
        total = 0
        productos_factura = []

        # Calcular el total y recopilar los detalles de los productos
        for item in carrito:
            producto = item["producto"]
            cantidad = item["cantidad"]
            subtotal = producto.precioProducto * cantidad
            total += subtotal
            productos_factura.append({
                "id": producto.idProducto,
                "nombre": producto.nombreProducto,
                "precio": producto.precioProducto,
                "cantidad": cantidad,
                "subtotal": subtotal
            })

        
        # Crear la factura en la base de datos
        nueva_factura = Factura(
            fechaFactura=fecha,
            subTotalFactura=total,
            cliente_idcliente=current_user.idCliente  # Aquí debes especificar el ID del cliente actual
        )
        db.session.add(nueva_factura)
        db.session.commit()
        print(len(productos_factura))

        # Agregar los detalles de los productos a la factura
        for item in carrito:
            producto = item["producto"]
            cantidad = item["cantidad"]
            subtotal = producto.precioProducto * cantidad
            detalle_factura = Detalle(
                cantidadDetalle=cantidad,
                Factura_idFactura=nueva_factura.idFactura,
                Producto_idProducto=producto.idProducto,
                subTotalDetalle=subtotal
            )
            db.session.add(detalle_factura)
            db.session.commit()
    
        # Vaciar el carrito después de completar la compra
        carrito_compras.vaciarcarrito()

        # Renderizar la plantilla de la factura con los datos necesarios
        return render_template('Carrito/factura.html', fecha=fecha, total=total, productos_factura=productos_factura)

    else:
        # Si el carrito está vacío, redirecciona al usuario a algún lugar apropiado
        return redirect(url_for('Productos.index'))

app/routes/Productos_routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from app.extesiones import db
from app.models.Categoria import Categoria
from app.models.Productos import Producto
from app.models.Cliente import Cliente
from flask_login import login_user, current_user, logout_user, login_required
import os

bp = Blueprint('Productos', __name__)


@bp.route("/Producto")
@login_required
def index():

    nameuser = current_user.nombreCliente  # Reemplaza esto con la obtención del nombre de usuario
    pl = nameuser[1] if nameuser else "No Hay Nombre"
    
    data = Producto.query.all()
    return render_template("Productos/index.html",  data=data, pl=pl)

@bp.route("/ProductoAdm")
@login_required
def indexAdm():
    
    data = Producto.query.all()
    return render_template("Productos/indexAdm.html",  data=data)

    


@bp.route("/Productos/add", methods=["GET", "POST"])
@login_required
def add():

    categoria = Categoria.query.all()
    if request.method == "POST":
        nombre = request.form["nombre"]
        detalle = request.form["detalle"]
        precio = request.form["precio"]
        stock = request.form["stock"]
        imagen = request.files["imag"]
        categoria = request.form["categoria"]
        

        NProducto = Producto(
            nombreProducto=nombre,
            detalleProducto=detalle,
            precioProducto=precio,
            stockProducto=stock,
            Categoria_idCategoria=categoria,
            imgp=imagen.filename,
        )
        db.session.add(NProducto)
        db.session.commit()
        
        if "imag" in request.files:
            foto = request.files["imag"]
            if foto.filename != "":
                saveimg(foto)
                
        return redirect(url_for("Productos.indexAdm"))
    
    
    return render_template("Productos/add.html", Categorias=categoria )


@bp.route("/Productos/edit/<int:id>", methods=["GET", "POST"])
@login_required

def edit(id):
    producto = Producto.query.get_or_404(id)
    categoriia = Categoria.query.all()

    if request.method == "POST":
        producto.nombreProducto = request.form["nombre"]
        producto.detalleProducto = request.form["detalle"]
        producto.precioProducto = request.form["precio"]
        producto.stockProducto = request.form["stock"]
        producto.Categoria_idCategoria = request.form["categoria"]
        
        
        if "imag" in request.files:
            foto = request.files["imag"]
            
            if foto.filename != "":
                deleteimg(producto.idProducto)
                print(producto.imgp)
                producto.imgp = foto.filename
                print(foto.filename)
                print(producto.imgp)
                saveimg(foto)

              
        print(producto.imgp)
        db.session.commit()
        print(producto.imgp)

        return redirect(url_for("Productos.indexAdm"))

    return render_template("Productos/edit.html", producto=producto, categoriia=categoriia)


@bp.route("/Productos/delete/<int:id>")
@login_required

def delete(id):
    detal = Producto.query.get_or_404(id)
    deleteimg(id)

    db.session.delete(detal)
    db.session.commit()

    return redirect(url_for("Productos.indexAdm"))



def saveimg(file):
    from run import app
    
    filename = file.filename 
    destination = os.path.join(app.root_path,"static","imagenes")
    file.save(
        os.path.join(destination,filename)
    )
    
    
    
def deleteimg(idProducto):
    from run import app
    
    imgpr = Producto.query.get_or_404(idProducto).imgp
    rutaimg = os.path.join(app.root_path,"static","imagenes", imgpr)
    if os.path.exists(rutaimg):
        os.remove(rutaimg)
    
    

app/templates/Productos/List.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Autor</title>
</head>
<body>
    <h1>Carrito</h1>
    <table>
        <tr>
            <th>Producto</th>
            <th>Precio</th>
            <th>Cantidad</th>
            <th>Acciones</th>
        </tr>
        {% for item in items %}
        
            <tr>
                <td>{{ item['producto'].nombreproducto }}</td>
                <td>{{ item['producto'].precioproducto }}</td>
                <td>{{ item['cantidad'] }}</td>
                <td>
                    Acciones               
                    <!-- Agrega aquí el enlace para eliminar -->
                </td>
            </tr>
        {% endfor %}        
    </table>
    <a href="{{ url_for('factura.add') }}">Generar factura</a>
</body>
</html>

app/templates/Productos/add.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" /> <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/css/bootstrap.min.css">
    <script src="{{ url_for('static', filename='bootstrap-5.3.0/js/bootstrap.bundle.js') }}"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='estilo.css') }}"
    />
    <title id="ttt" >Agregar Producto</title>
    <style>
      body{
        background-image: url('{{ url_for("static", filename="/imagenes/gifac.gif") }}');
        background-size: cover;
        background-position: center;
        display: flex;
        color: aqua;
        align-items: center;
        justify-content: center;
    }
      h1{
        color: aqua;
      }
      #bka{
        background-color: black;
        display: flex;
        width: 430px;
        align-items: center;
      }
    </style>
  </head>
  <body>
    
     <div id="bka" ><form action="{{ url_for('Productos.add') }}" method="post" enctype="multipart/form-data">
      <h1 id="ttt" >  Agregar Producto</h1>
      <label for="nombre">Nombre:</label>
      <input type="text" id="nombre" name="nombre" required class="form-control" />
      <label for="detalle">Detalle:</label>
      <input type="text" id="detalle" name="detalle" required class="form-control" />
      <label for="precio">Precio:</label>
      <input type="number" id="precio" name="precio" required class="form-control" />
      <label for="stock">Stock:</label>
      <input type="number" id="stock" name="stock" required class="form-control" />
      <label for="imag">Imagen:</label>
      <input type="file" id="imag" name="imag" accept=".png,.jpg,.jpng,.webp" required class="form-control" />
      <label for="categoria">Categoria:</label>
      <select name="categoria" id="categoria">
        {% for categoria in Categorias %}
        <option value="{{ categoria.idCategoria }}">{{ categoria.nombreCategoria }}</option>
        {% endfor %}
      </select>
      <button type="submit">Agregar Producto</button>
    </div>
    </form>
  </body>
</html>

app/templates/Productos/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='estilo.css') }}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/css/bootstrap.min.css">
    <script src="{{ url_for('static', filename='bootstrap-5.3.0/js/bootstrap.bundle.js') }}"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <title>Editar Producto</title>
</head>
<body>
    <h1>Editar Producto</h1>
    <form action="{{ url_for('Productos.edit', id=producto.idProducto) }}" method="post"  enctype="multipart/form-data" >
        <label for="nombre">Nombre:</label>
        <input type="text" id="nombre" name="nombre" value="{{ producto.nombreProducto }}" required>
        <label for="detalle">Detalle:</label>
        <input type="text" id="detalle" name="detalle" value="{{ producto.detalleProducto }}" required>
        <label for="precio">Precio:</label>
        <input type="text" id="precio" name="precio" value="{{ producto.precioProducto }}" required>
        <label for="stock">Stock:</label>
        <input type="text" id="stock" name="stock" value="{{ producto.stockProducto }}" required>
        <label for="imag">Imagen:</label>
        <input type="file" id="imag" name="imag" accept=".png,.jpg,.jpng,.webp"  > 
        <img src=" {{ url_for('static',filename='imagenes/'+producto.imgp) }} " alt=""> <br>
        

        <label for="categoria">Categoria:</label>
         
       
            <select name="categoria" id="categoria"> 
                <option value="{{ producto.categor.idCategoria }}" selected> {{ producto.categor.nombreCategoria }} </option>

                {% for categoria in categoriia %}
                    {% if producto.categor.idCategoria != categoria.idCategoria %} 
                        <option value="{{ categoria.idCategoria }}">{{ categoria.nombreCategoria }}</option>
                    {% endif %}
              
                {% endfor %}
              </select>
        
        <button type="submit">Actualizar Producto:</button>
    </form>
</body>
</html>

app/templates/Productos/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='estiloi.css') }}"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/css/bootstrap.min.css"
    />
    <script src="{{ url_for('static', filename='bootstrap-5.3.0/js/bootstrap.bundle.js') }}"></script>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />

    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='estilo.css') }}"
    />
    <title>Productos</title>
    <style>
      body {
        background-image: url('{{ url_for("static", filename="/imagenes/gifp.gif") }}');
        background-size: cover;
        background-attachment: fixed;
        background-position: center;
        color: aqua;
      }
      nav {
        background-color: black;
        display: flex;
        align-items: center;
        flex-direction: row;
        justify-content: center;
        display: contents;
      }
      li {
        text-size-adjust: 5px;
        color: aqua;
      }
      #col {
        color: aqua;
      }
      ul{
        display: flex;
        justify-content: center;
        align-items: center;
      }
      .container {
        display: grid;
        grid-template-columns: repeat(3, 1fr); /* 3 columnas de igual tamaño */
        grid-gap: 70px; 
        
    }
    
    @media screen and (max-width: 800px) {
        .container {
            grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
        }
    }
    
    @media screen and (max-width: 600px) {
        .container {
            grid-template-columns: repeat(auto-fit, minmax(100px, 1fr));
        }
    }
    .colw{
        color: white !important;
    }
    .l{
      padding: 0 10px;
    }
    footer {
      background-color: black;
      padding: 20px;
      text-align: center;
  }
  
  .contact-info p {
      margin: 5px;
      font-size: 16px;
  }
    </style>
  </head>
  
  <body>
      <div id="fondg" class="container">
          <br>
          <nav>
        <ul>
          <li><img src=" {{ url_for("static", filename="/imagenes/logo.jpg")}}" style="width: 150px; height: 150px; " alt=""> </li>
            <li><a id="col" href="cursos.html">Cursos</a></li>
            <li><a id="col" href="#">Noticias</a></li>
            <li><a class="dropdown-item " href="{{url_for('Administrador.logout')}}" >Cerrar session</a ></li>
            <li>  
            <div class="btn-group">
              <div>
                <div class="pha">
                  <div class="mss">
                    <div id="hp">
                      <strong class="l" id="gmr"> {{ current_user.pl }}</strong>
                    </div>
                  </div>
                </div>
              </div>
              

                
              </ul>
            </div>
          </li>
        </ul>
      </nav>
      <br>  
      <center><h1 id="col" >Productos</h1></center>
      <br>
       <!-- <table class="table">
        <thead>
          <tr>
            <th>ID</th>
            <th>IMG</th>
            <th>Nombre</th>
            <th>Detalle</th>
            <th>Precio</th>
            <th>Stock</th>
            <th>Categoría</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          {% for Producto in data %}
          <tr>
            <td>{{ Producto.idProducto }}</td>
            <td>
              <img
                src=" {{ url_for('static',filename='imagenes/'+Producto.imgp) }} "
                alt=""
              />
            </td>
            <td>{{ Producto.nombreProducto }}</td>
            <td>{{ Producto.detalleProducto }}</td>
            <td>{{ Producto.precioProducto }}</td>
            <td>{{ Producto.stockProducto }}</td>
            <td>{{ Producto.categor.nombreCategoria }}</td>
            <td>
              <form
                action="{{ url_for('carritos.agregar_al_carrito', id = Producto.idProducto) }}"
                method="post"
              >
                <input type="number" name="cantidad" value="1" min="1" />
                <button type="submit">Agregar al carrito</button>
              </form>
            </td>
          </tr>

          {% endfor %}
        </tbody>
      </table> -->
      <div class="container" >
        {% for Producto in data %}

        <div class="card" style="align-items: center; border-radius: 16px; border-color: aqua; border-width: 10px; background: black;
        color: white;"  >
            <img  src=" {{ url_for('static',filename='imagenes/'+Producto.imgp) }} "  style="
            height: 250px;     width: 100%;     ; " class="card-img-top" alt="...">
            <div  class="card-body colw">
              <h5 class="card-title colw"> {{ Producto.nombreProducto }} </h5>
              <h6 class="card-subtitle mb-2 text-body-secondary colw ">Precio: ${{ Producto.precioProducto }}</h6>
              <h6 class="card-subtitle mb-2 text-body-secondary colw "> Disponible: {{ Producto.stockProducto }}</h6>
              <form
              action="{{ url_for('carritos.agregar_al_carrito', id = Producto.idProducto) }}"
              method="post"
            >
              <input type="number" name="cantidad" value="1" min="1" />
              <button onmouseover="this.style.transform='scale(1)'" type="submit"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart-plus-fill" viewBox="0 0 16 16">
                <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0m7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0M9 5.5V7h1.5a.5.5 0 0 1 0 1H9v1.5a.5.5 0 0 1-1 0V8H6.5a.5.5 0 0 1 0-1H8V5.5a.5.5 0 0 1 1 0"/>
              </svg></button>
            </form> 
            </div>
          </div>
          
        {% endfor %}
        <br>
      </div><br>
      
      <center>
      <a href="{{ url_for('carritos.index') }}" class="btn btn-primary">Ir a Carrito</a> <br>
      </center>
    </div><br>
    <footer>
      <div class="contact-info">
          <p>Teléfono: 321-956-6428</p>
          <p>Correo: sebastianhellsing1999@gmail.com</p>
      </div>
  </footer>
    <!-- Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </body>
</html>

app/templates/Productos/indexAdm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/css/bootstrap.min.css">
    <script src="{{ url_for('static', filename='bootstrap-5.3.0/js/bootstrap.bundle.js') }}"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <link rel="stylesheet" href="{{ url_for('static', filename='estilo.css') }}">
    <title>Productos</title>
</head>
<body>
    <div class="container">
        <h1>Productos</h1>
        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>IMG</th>
                    <th>Nombre</th>
                    <th>Detalle</th>
                    <th>Precio</th>
                    <th>Stock</th>
                    <th>Categoría</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for Producto in data %}
                    <tr>
                        <td>{{ Producto.idProducto }}</td>
                        <td> <img style="width: 250px; height: 250px; " src=" {{ url_for('static',filename='imagenes/'+Producto.imgp) }} " alt=""> </td>
                        <td>{{ Producto.nombreProducto }}</td>
                        <td>{{ Producto.detalleProducto }}</td>
                        <td>{{ Producto.precioProducto }}</td>
                        <td>{{ Producto.stockProducto }}</td>
                        <td>{{ Producto.categor.nombreCategoria }}</td>
                        <td>
                            <a href="{{ url_for('Productos.edit', id=Producto.idProducto) }}" class="btn btn-primary">Editar</a>
                            <a href="{{ url_for('Productos.delete', id=Producto.idProducto) }}" class="btn btn-danger">Eliminar</a>
                            <form action="{{ url_for('carritos.agregar_al_carrito', id = Producto.idProducto) }}" method="post">
                                <input type="number" name="cantidad" value="1" min="1">
                                <button type="submit">Agregar al carrito</button>
                            </form>
                        </td>
                    </tr>

                {% endfor %}
            </tbody>
        </table>
        <a href="{{ url_for('Productos.add') }}" class="btn btn-success">Agregar Producto</a><br>
        <a href="{{ url_for('Administrador.index') }}" class="btn btn-secondary">Ir a Administrador</a>
        <a href="{{ url_for('carritos.index') }}" class="btn btn-primary">Ir a Carrito</a>

    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-circle"
                             viewBox="0 0 16 16">
                        <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
                        <path fill-rule="evenodd"
                              d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z" />
                        </svg>
    <div class='btn-group'>
        <button type='button' class='btn btn-tranparent dropdown-toggle' style='padding: 0; border: none; display: flex; align-items: center; gap: 5px;' data-bs-toggle='dropdown' aria-expanded='false' id='btnTogglee'>
            <strong>{{ current_user.direccionCliente }}</strong>  
        </button>
        <ul class='dropdown-menu' style='padding-left:10px; '>
            <li><a class='dropdown-items' href='#'>Perfil</a></li>
            
            <li><hr class='dropdown-divider'></li>
            <li><a class='dropdown-item' href="{{url_for('Administrador.logout')}}">Cerrar session</a></li>
        </ul>
    </div>
    </div>
    <!-- Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>