app/models/Detalle.py
from app.extesiones import db
from sqlalchemy.orm import relationship

class Detalle(db.Model):
    idDetalle = db.Column(db.Integer, primary_key=True)
    cantidadDetalle = db.Column(db.Integer, nullable=True)
    Factura_idFactura = db.Column(db.Integer, db.ForeignKey('factura.idFactura'), nullable=False)
    subTotalDetalle = db.Column(db.String(45), nullable=True)
    Producto_idProducto = db.Column(db.Integer, db.ForeignKey('producto.idProducto'), nullable=False)
    allp = db.relationship("Producto")

app/routes/Detalle_routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from app.extesiones import db
from app.models.Detalle import Detalle

bp = Blueprint("Detalle", __name__)


@bp.route("/Detalle")
def index():
    data = Detalle.query.all()
    return render_template("Detalle/index.html", data=data)


@bp.route("/Detalle/add", methods=["GET", "POST"])
def add():
    if request.method == "POST":
        cantidad = request.form["cantidad"]
        subtotal = request.form["subtotal"]
        factura = request.form["factura"]
        producto = request.form["producto"]

        NDetalle = Detalle(
            cantidadDetalle=cantidad,
            subTotalDetalle=subtotal,
            Factura_idFactura=factura,
            Producto_idProducto=producto,
        )
        db.session.add(NDetalle)
        db.session.commit()

        return redirect(url_for("Detalle.index"))

    return render_template("Detalle/add.html")


@bp.route("/Detalle/edit/<int:id>", methods=["GET", "POST"])
def edit(id):
    detalle = Detalle.query.get_or_404(id)

    if request.method == "POST":
        detalle.cantidad = request.form["cantidad"]
        detalle.subtotal = request.form["subtotal"]
        detalle.factura = request.form["factura"]
        detalle.producto = request.form["producto"]
        db.session.commit()
        return redirect(url_for("Detalle.index"))

    return render_template("Detalle/edit.html", detalle=detalle)


@bp.route("/Detalle/delete/<int:id>")
def delete(id):
    detal = Detalle.query.get_or_404(id)

    db.session.delete(detal)
    db.session.commit()

    return redirect(url_for("Detalle.index"))

app/templates/Detalle/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='estilo.css') }}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/css/bootstrap.min.css">
    <script src="{{ url_for('static', filename='bootstrap-5.3.0/js/bootstrap.bundle.js') }}"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <title>Agregar Detalle</title>
</head>
<body>
    <h1>Agregar Detalle</h1>
    <form action="{{ url_for('Detalle.add') }}" method="post">
        <label for="cantidad">Cantidad:</label>
        <input type="number" id="cantidad" name="cantidad" required>
        <label for="subtotal">Subtotal:</label>
        <input type="number" id="subtotal" name="subtotal" required>
        <label for="cantidad">Factura:</label>
        <input type="email" id="cantidad" name="cantidad" required>
        <label for="producto">Producto:</label>
        <input type="number" id="producto" name="producto" required>
     
        <button type="submit">Agregar Detalle</button>
    </form>
</body>
</html>

app/templates/Detalle/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='estilo.css') }}">
    <title>Editar Nombre</title>
</head>
<body>
    <h1>Editar Nombre</h1>
    <form action="{{ url_for('Detalle.edit', id=detalle.idDetalle) }}" method="post">
        <label for="cantidad">Cantidad:</label>
        <input type="text" id="cantidad" name="cantidad" value="{{ detalle.cantidadDetalle }}" required>
        <label for="subtotal">Subtotal:</label>
        <input type="text" id="subtotal" name="subtotal" value="{{ detalle.subTotalDetalle }}" required>
        <label for="factura">Factura:</label>
        <input type="text" id="factura" name="factura" value="{{ detalle.Factura_idFactura }}" required>
        <label for="producto">Productos:</label>
        <input type="text" id="producto" name="producto" value="{{ detalle.Producto_idProducto }}" required>
        <button type="submit">Actualizar Cliente:</button>
    </form>
</body>
</html>

app/templates/Detalle/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='estilo.css') }}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/css/bootstrap.min.css">
    <script src="{{ url_for('static', filename='bootstrap-5.3.0/js/bootstrap.bundle.js') }}"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>Clientes</title>
</head>
<body>
    <div class="container">
        <h1>Detalles</h1>
        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Cantidad</th>
                    <th>SubTotal</th>
                    <th>Factura</th>
                    <th>Producto</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for Detalle in data %}
                    <tr>
                        <td>{{ Detalle.idDetalle }}</td>
                        <td>{{ Detalle.cantidadDetalle }}</td>
                        <td>{{ Detalle.subTotalDetalle }}</td>
                        <td>{{ Detalle.Factura_idFactura }}</td>
                        <td>{{ Detalle.Producto_idProducto }}</td>
                        <td>
                            <a href="{{ url_for('Detalle.edit', id=Detalle.idDetalle) }}" class="btn btn-primary">Editar</a>
                            <a href="{{ url_for('Detalle.delete', id=Detalle.idDetalle) }}" class="btn btn-danger">Eliminar</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <a href="{{ url_for('Detalle.add') }}" class="btn btn-success">Agregar Detalle</a><br>
        <a href="{{ url_for('Administrador.index') }}" class="btn btn-secondary">Ir a Administrador</a>
    </div>
    <!-- Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>